// eLABORADO POR KAREN LORENA MOLANO ARIAS CC 1002543562 Y JUAN JOSE RAMIREZ GUTIERREZ CC 1002543562
// LENGUAJE DE PROGRAMACION AVANZADA 1 - 2023-2 UNIREMINGTON

package vista;

import bean.Vehiculo;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.DefaultEditorKit;
import modelo.ArregloVehiculo;

public class JFVehiculo extends javax.swing.JFrame {

    ArregloVehiculo listaVehi = new ArregloVehiculo();
    DefaultTableModel modelo;
    /* Manejo de Archivos */
    JFileChooser elegir = new JFileChooser(".");
    FileInputStream entrada = null;

    public JFVehiculo() {
        initComponents();
        txtCodigoR.setText(String.valueOf(listaVehi.totalVehi() + 1));
        this.setLocationRelativeTo(null);
        modelo = (DefaultTableModel) tblListaVehi.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtFilTipov = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtpCRUDVehi = new javax.swing.JTabbedPane();
        jpCVehi = new javax.swing.JPanel();
        btnListar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListaVehi = new javax.swing.JTable();
        jpMVehi = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtCodigoM = new javax.swing.JTextField();
        btnBuscarM = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnLimpiarM = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        txtTipovM = new javax.swing.JTextField();
        btnActualizar = new javax.swing.JButton();
        jpEVehi = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtCodigoE = new javax.swing.JTextField();
        btnBuscarE = new javax.swing.JButton();
        jpRVehi = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCodigoR = new javax.swing.JTextField();
        txtTipovR = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        btnLimpiarR = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        txtFilTipov.setEditable(false);
        txtFilTipov.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtFilTipov.setBorder(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(" VEHÍCULO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 500, 35));

        jtpCRUDVehi.setBackground(new java.awt.Color(117, 117, 117));
        jtpCRUDVehi.setForeground(new java.awt.Color(255, 255, 255));
        jtpCRUDVehi.setFocusable(false);
        jtpCRUDVehi.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtpCRUDVehi.setMinimumSize(new java.awt.Dimension(860, 500));
        jtpCRUDVehi.setPreferredSize(new java.awt.Dimension(860, 500));

        jpCVehi.setBackground(new java.awt.Color(255, 255, 255));
        jpCVehi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jpCVehi.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnListar.setBackground(new java.awt.Color(117, 117, 117));
        btnListar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnListar.setForeground(new java.awt.Color(255, 255, 255));
        btnListar.setText("MOSTRAR VEHICULOS");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });
        jpCVehi.add(btnListar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 460, 40));

        tblListaVehi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblListaVehi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MATRICULA DEL VEHICULO", "TIPOVEHICULO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblListaVehi.setGridColor(new java.awt.Color(255, 255, 255));
        tblListaVehi.setSelectionBackground(new java.awt.Color(245, 245, 245));
        tblListaVehi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblListaVehiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblListaVehi);

        jpCVehi.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 460, 160));

        jtpCRUDVehi.addTab("CONSULTAR", jpCVehi);

        jpMVehi.setBackground(new java.awt.Color(255, 255, 255));
        jpMVehi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jpMVehi.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("ID DEL VEHÍCULO:");
        jpMVehi.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 140, 25));

        txtCodigoM.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jpMVehi.add(txtCodigoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 200, 25));

        btnBuscarM.setBackground(new java.awt.Color(117, 117, 117));
        btnBuscarM.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnBuscarM.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarM.setText("BUSCAR");
        btnBuscarM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarMActionPerformed(evt);
            }
        });
        jpMVehi.add(btnBuscarM, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 200, 40));
        jpMVehi.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 470, 10));

        btnLimpiarM.setBackground(new java.awt.Color(117, 117, 117));
        btnLimpiarM.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnLimpiarM.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiarM.setText("LIMPIAR");
        btnLimpiarM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarMActionPerformed(evt);
            }
        });
        jpMVehi.add(btnLimpiarM, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 200, 40));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Tipo de Vehiculo");
        jpMVehi.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 180, 25));

        txtTipovM.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTipovM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTipovMActionPerformed(evt);
            }
        });
        jpMVehi.add(txtTipovM, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 220, 25));

        btnActualizar.setBackground(new java.awt.Color(117, 117, 117));
        btnActualizar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setText("ACTUALIZAR");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jpMVehi.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 200, 40));

        jtpCRUDVehi.addTab("MODIFICAR", jpMVehi);

        jpEVehi.setBackground(new java.awt.Color(255, 255, 255));
        jpEVehi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jpEVehi.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("INGRESAR EL ID DEL TIPO DF VEHÍCULO:");
        jpEVehi.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 410, 30));

        txtCodigoE.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jpEVehi.add(txtCodigoE, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 240, 30));

        btnBuscarE.setBackground(new java.awt.Color(117, 117, 117));
        btnBuscarE.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnBuscarE.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarE.setText("ELIMINAR");
        btnBuscarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarEActionPerformed(evt);
            }
        });
        jpEVehi.add(btnBuscarE, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 290, 40));

        jtpCRUDVehi.addTab("ELIMINAR", jpEVehi);

        jpRVehi.setBackground(new java.awt.Color(255, 255, 255));
        jpRVehi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jpRVehi.setMaximumSize(new java.awt.Dimension(860, 460));
        jpRVehi.setMinimumSize(new java.awt.Dimension(860, 460));
        jpRVehi.setPreferredSize(new java.awt.Dimension(800, 460));
        jpRVehi.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("ID:");
        jpRVehi.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 30, 180, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("MARCA:");
        jpRVehi.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 70, 180, 30));

        txtCodigoR.setBackground(new java.awt.Color(255, 255, 255));
        txtCodigoR.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtCodigoR.setOpaque(true);
        txtCodigoR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoRActionPerformed(evt);
            }
        });
        txtCodigoR.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoRKeyTyped(evt);
            }
        });
        jpRVehi.add(txtCodigoR, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 220, 30));

        txtTipovR.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTipovR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTipovRActionPerformed(evt);
            }
        });
        jpRVehi.add(txtTipovR, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 220, 30));

        btnRegistrar.setBackground(new java.awt.Color(117, 117, 117));
        btnRegistrar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setText("GUARDAR");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jpRVehi.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 220, 40));

        btnLimpiarR.setBackground(new java.awt.Color(117, 117, 117));
        btnLimpiarR.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnLimpiarR.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiarR.setText("LIMPIAR");
        btnLimpiarR.setToolTipText("");
        btnLimpiarR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarRActionPerformed(evt);
            }
        });
        jpRVehi.add(btnLimpiarR, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 220, 40));

        jtpCRUDVehi.addTab("REGISTRAR", jpRVehi);

        jPanel1.add(jtpCRUDVehi, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 100, 520, 310));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("SELECCIONE EL TIPO DE");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 500, 35));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblListaVehiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblListaVehiMouseClicked
        if (evt.getClickCount() == 1) {

        }
        if (evt.getClickCount() == 2) {
            enviarVehiculo();
        }
    }//GEN-LAST:event_tblListaVehiMouseClicked

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        listar();
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnBuscarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarEActionPerformed
        eliminar();
    }//GEN-LAST:event_btnBuscarEActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        actualizar();
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void txtTipovMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTipovMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTipovMActionPerformed

    private void btnLimpiarMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarMActionPerformed
        limpiarM();
    }//GEN-LAST:event_btnLimpiarMActionPerformed

    private void btnBuscarMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarMActionPerformed
        buscar();
    }//GEN-LAST:event_btnBuscarMActionPerformed

    private void btnLimpiarRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarRActionPerformed
        limpiarR();
    }//GEN-LAST:event_btnLimpiarRActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        guardar();
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void txtTipovRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTipovRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTipovRActionPerformed

    private void txtCodigoRKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoRKeyTyped
        char c = evt.getKeyChar();
        if (Character.isDigit(c)) {

        } else {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_txtCodigoRKeyTyped

    private void txtCodigoRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoRActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFVehiculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscarE;
    private javax.swing.JButton btnBuscarM;
    private javax.swing.JButton btnLimpiarM;
    private javax.swing.JButton btnLimpiarR;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel jpCVehi;
    private javax.swing.JPanel jpEVehi;
    private javax.swing.JPanel jpMVehi;
    private javax.swing.JPanel jpRVehi;
    public static javax.swing.JTabbedPane jtpCRUDVehi;
    private javax.swing.JTable tblListaVehi;
    private javax.swing.JTextField txtCodigoE;
    private javax.swing.JTextField txtCodigoM;
    private javax.swing.JTextField txtCodigoR;
    private javax.swing.JTextField txtFilTipov;
    private javax.swing.JTextField txtTipovM;
    private javax.swing.JTextField txtTipovR;
    // End of variables declaration//GEN-END:variables
/**
     * ************** REGISTRAR *************
     */
    private void guardar() {

        boolean validar = txtCodigoR.getText().equals("") || txtTipovR.getText().equals("");

        if (!validar) {
            try {
                Vehiculo p = new Vehiculo(codigoR(), tipovR());
                String respuesta = listaVehi.adicionar(p);
                if (respuesta.equals("Vehículo guardado correctamente")) {

                }
                listaVehi.grabar();
                JOptionPane.showMessageDialog(null, respuesta);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error al guardar: " + e.toString());
            }
        } else {
            JOptionPane.showMessageDialog(null, "Le falto rellenar un campos o ingreso un dato errómeo.");
        }

    }

    private int codigoR() {
        return Integer.parseInt(txtCodigoR.getText());
    }

    private String tipovR() {
        return txtTipovR.getText();
    }

    /**
     * ************** LIMPIAR *************
     */
    private void limpiarR() {
        txtCodigoR.setText(String.valueOf(listaVehi.totalVehi() + 1));
        txtTipovR.setText("");
        txtCodigoR.requestFocus(); //Focus
    }

    private void limpiarM() {
        txtCodigoM.setText("");
        txtTipovM.setText("");
        txtCodigoM.requestFocus(); //Focus
    }

    private void listar() {
        //limpiarR la tabla
        int filas = tblListaVehi.getRowCount();
        for (int i = 0; i < filas; i++) {
            modelo.removeRow(0);
        }

        String filtro = txtFilTipov.getText();
        if (filtro.trim().equals("")) {
            //agregar la lista a la tabla
            if (listaVehi.totalVehi() > 0) {
                for (int i = 0; i < listaVehi.totalVehi(); i++) {
                    modelo.addRow(new Object[]{
                        listaVehi.obtener(i).getCodigo(),
                        listaVehi.obtener(i).getTipov(),
                        listaVehi.obtener(i).getCosto()});
                }
            } else {
                JOptionPane.showMessageDialog(null, "No hay vehículos para mostrar");
            }
        } else {
            if (listaVehi.obtTipov(filtro).size() > 0) {
                for (int i = 0; i < listaVehi.obtTipov(filtro).size(); i++) {
                    modelo.addRow(new Object[]{
                        listaVehi.obtTipov(filtro).get(i).getCodigo(),
                        listaVehi.obtTipov(filtro).get(i).getTipov(),
                        listaVehi.obtTipov(filtro).get(i).getCosto()});
                }
            } else {
                JOptionPane.showMessageDialog(null, "No hay vehículos para mostrar");
            }
        }
    }

    private void buscar() {
        try {
            if (rootPaneCheckingEnabled) {
                int cod = codigoM();
                Vehiculo p = null;
                p = listaVehi.buscar(cod);
                mostrarVehiculo(p);
            }
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(null, "El código ingresado no existe");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Los códigos son de tipo numérico.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error en buscar: " + e);
        }
    }

    private void mostrarVehiculo(Vehiculo p) {
        txtTipovM.setText(p.getTipov());
    }

    private void actualizar() {
        boolean validar = txtCodigoM.getText().equals("") || txtTipovM.getText().equals("");

        if (!validar) {
            try {
                Vehiculo p = new Vehiculo(codigoM(), tipovM());
                listaVehi.actualizar(p);
                listaVehi.grabar();
                JOptionPane.showMessageDialog(null, "Actualización realizada con éxito");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error al actualizar: " + e.toString());
            }
        } else {
            JOptionPane.showMessageDialog(null, "Rellena todos los campos.");
        }
    }

    private int codigoM() {
        return Integer.parseInt(txtCodigoM.getText());
    }

    private String tipovM() {
        return txtTipovM.getText();
    }

    private void eliminar() {
        try {
            Vehiculo v = null;
            v = listaVehi.buscar(codigoE());
            int elecc = JOptionPane.showConfirmDialog(null, "Está seguro de eliminar el vehículo " + v.getTipov());
            if (elecc == 0) {
                listaVehi.eliminar(v);
                listaVehi.grabar();
                JOptionPane.showMessageDialog(null, "Eliminación realizada con éxito");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "El código no existe");
        }
    }

    private int codigoE() {
        return Integer.parseInt(txtCodigoE.getText());
    }

    private void enviarVehiculo() {
        int fila = tblListaVehi.getSelectedRow();
        if (fila >= 0) {
            int pos = (int) tblListaVehi.getValueAt(fila, 0);
            Vehiculo v = listaVehi.buscar(pos);
            JFPrincipal.lblNombreVehi.setText(v.getTipov());
            JFPrincipal.veh = v;
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Selecciona una fila de la Tabla para enviar los datos");
        }
    }

}
